// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOT0q_pQ5Mmtt9L4SpXLPc877eOS6vyYk',
    appId: '1:564235304621:android:2100d81806b942a5a89024',
    messagingSenderId: '564235304621',
    projectId: 'tictactoepvp-8c663',
    storageBucket: 'tictactoepvp-8c663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsuNZWJPCXdwBwtFnV35kVfUiHX-JtAxY',
    appId: '1:564235304621:ios:a7f11c8046708562a89024',
    messagingSenderId: '564235304621',
    projectId: 'tictactoepvp-8c663',
    storageBucket: 'tictactoepvp-8c663.firebasestorage.app',
    iosBundleId: 'com.example.tictactoepvp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJTospMVvITgAzlCqzvK1odI74YGc-RM',
    appId: '1:564235304621:web:757e4d4ffd05bed4a89024',
    messagingSenderId: '564235304621',
    projectId: 'tictactoepvp-8c663',
    authDomain: 'tictactoepvp-8c663.firebaseapp.com',
    storageBucket: 'tictactoepvp-8c663.firebasestorage.app',
    measurementId: 'G-3T3N1FFM8H',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGJTospMVvITgAzlCqzvK1odI74YGc-RM',
    appId: '1:564235304621:web:f9fdb266d4e4a321a89024',
    messagingSenderId: '564235304621',
    projectId: 'tictactoepvp-8c663',
    authDomain: 'tictactoepvp-8c663.firebaseapp.com',
    storageBucket: 'tictactoepvp-8c663.firebasestorage.app',
    measurementId: 'G-9NGN0Q30MC',
  );

}