// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4RYqlr9QPtuJvI1og-H4m44zaoqlb6r4',
    appId: '1:559612395421:web:13c32f49832fa45ac13974',
    messagingSenderId: '559612395421',
    projectId: 'gatomultiplayer-e2706',
    authDomain: 'gatomultiplayer-e2706.firebaseapp.com',
    databaseURL: 'https://gatomultiplayer-e2706-default-rtdb.firebaseio.com',
    storageBucket: 'gatomultiplayer-e2706.firebasestorage.app',
    measurementId: 'G-D8Z933660X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpb1_MDOoL55g0MfUmR92PXkk_vnA9eDs',
    appId: '1:559612395421:android:a2947400443560eac13974',
    messagingSenderId: '559612395421',
    projectId: 'gatomultiplayer-e2706',
    databaseURL: 'https://gatomultiplayer-e2706-default-rtdb.firebaseio.com',
    storageBucket: 'gatomultiplayer-e2706.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVG9whVGDQw2WrUH0GtVd3D4bzt0Dc51I',
    appId: '1:559612395421:ios:f62b244c343fd7a5c13974',
    messagingSenderId: '559612395421',
    projectId: 'gatomultiplayer-e2706',
    databaseURL: 'https://gatomultiplayer-e2706-default-rtdb.firebaseio.com',
    storageBucket: 'gatomultiplayer-e2706.firebasestorage.app',
    iosClientId: '559612395421-f6t8th00f13rq01eitq0sv05mcvjie2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.gatoMultiplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVG9whVGDQw2WrUH0GtVd3D4bzt0Dc51I',
    appId: '1:559612395421:ios:f62b244c343fd7a5c13974',
    messagingSenderId: '559612395421',
    projectId: 'gatomultiplayer-e2706',
    databaseURL: 'https://gatomultiplayer-e2706-default-rtdb.firebaseio.com',
    storageBucket: 'gatomultiplayer-e2706.firebasestorage.app',
    iosClientId: '559612395421-f6t8th00f13rq01eitq0sv05mcvjie2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.gatoMultiplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4RYqlr9QPtuJvI1og-H4m44zaoqlb6r4',
    appId: '1:559612395421:web:e78b7ce585fac7b2c13974',
    messagingSenderId: '559612395421',
    projectId: 'gatomultiplayer-e2706',
    authDomain: 'gatomultiplayer-e2706.firebaseapp.com',
    databaseURL: 'https://gatomultiplayer-e2706-default-rtdb.firebaseio.com',
    storageBucket: 'gatomultiplayer-e2706.firebasestorage.app',
    measurementId: 'G-DWKD43L27J',
  );
}
